### ISSUE TITLE
Option to print new progressbar only when progress is actually achieved

### ISSUE THREAD

**Issue by GenosseFlosse** [JAAdrian/MatlabProgressBar#8]
Hi,
I have the use case for a progressbar where I want the progressbar to be updated only when a new iteration was finished. What I do NOT want is a fixed updaterate, since this will print a lot of empty lines into my logfile. How can I achieve that with the current implementation? And if not, could you add this to the wishlist? 😄

**Comment by JAAdrian** [comment]
Hi! :wave: 

So, from what I understand, something like this would be desired, right?
You are fetching continuously something in a loop but only now and then, a concrete job ends or a result is returned.

Usually, everything which is not handled in the shortcut via the `progress()` function is handled via concrete calls to the bar object. Could this already help you?

```
bar = ProgressBar(10, ...);
while thingsAreRunning
    if interestingThingHasHappend
        bar.step([], [], []);
    end
end
bar.release();
```

**Comment by JAAdrian** [comment]
Hi @GenosseFlosse,
could I answer your question and can this issue be closed?
