### ISSUE TITLE
 Error in matlab.system.SystemProp.createVersionNumber

### ISSUE THREAD

**Issue by RSKothari** [JAAdrian/MatlabProgressBar#9]
I am not sure why this error occurs or even how to replicate it. It just pops up. If you have come across this, a solution would be great!

**Comment by JAAdrian** [comment]
Hi @RSKothari, 

I don't know that error.  
Have you already tried searching the web for this issue? It looks like a function shadowing issue...

**Comment by RSKothari** [comment]
Yeah, I did. It seems overloading a MATLAB core function results in this issue. Anyway, thanks for the time. Great effort!

**Comment by JAAdrian** [comment]
Thanks and sorry for the hassle! 

Hopefully you can fix this issue. Alternatively, you could try to check out the [last version of the 2.x.x major branch.](https://github.com/JAAdrian/MatlabProgressBar/releases/tag/2.9.7) This does not use a System Object but may also lack features. Not sure though, shame on me, the changelog was only introduced with v3.0.0 :man_facepalming:

**Comment by RSKothari** [comment]
Hi @JAAdrian the issue was because a copy of `strsplit` was present in my library of functions. This issue was noted and resolved [here](https://www.mathworks.com/matlabcentral/answers/509665-what-is-error-in-matlab-system-systemprop-createversionnumber#comment_1105949).

**Comment by JAAdrian** [comment]
Hey @RSKothari, thanks for the update! 
Nasty one, glad you were able to figure that one out 🤞
